### ISSUE TITLE
Make empty view on http://cfp.devday.pl/papers frendlier

### ISSUE THREAD

**Issue by kubawalinski** [abbdevday/cfp#13]
I don't know what we might add there, yet. Maybe somebody else has an idea?

**Comment by rafek** [comment]
Could it be as simpe as?

![0nf5blf 1](https://cloud.githubusercontent.com/assets/198978/7579788/a2175a76-f869-11e4-9538-cb37e0bacdb8.png)

**Comment by witchy-mutant** [comment]
I already put something simikar there. Thanks @rafek
