### ISSUE TITLE
Add Template with branding to account activation email

### ISSUE THREAD

**Issue by kubawalinski** [abbdevday/cfp#2]
I believe it might be required to at lest ad a DevDay logo and use some DD colours. Maybe add a footer with links to twitter/fb/website/yt?

**Comment by Biegal** [comment]
I've pushed in initail version of templating via razor views. One thing I need to dig deeper is how to exclude standard layout :/

**Comment by Biegal** [comment]
Ok @mihcall , basic templating should work now.
You can prepare templates as html views, see: Views\MailTemplates\RegisterConfirmation.cshtml
and Shared_LayoutMail.

Don't mind that there is <html> tag in RegisterConfirmation.cshtm, remove all but setting layout, and create just content there. Everything that should end up inside <body>

**Comment by Biegal** [comment]
There are now two emails to polish:
RegistrationConfirmation
ResetPassword
